### PR TITLE
Automatic PyPi wheel deployment

### LINKED ISSUE #7: Linux and Windows .whl releases
Sorry to bombard you with issues. Would you consider releasing wheels for this project in future? Especially for Windows where building is more challenging. This can be done with CI to avoid having to build these manually.

### PR DESCRIPTION
**Pull request by scottgigante**
Closes #7

### CODE REVIEW

**Review by jxz12 — APPROVED** [review]
Amazing work! Thank you :)

**Comment by scottgigante** [comment]
You're welcome!

**Comment by scottgigante** [comment]
I forgot to add: 

1. You might want to add CI badges to your README. Example: https://github.com/nmslib/nmslib/blob/master/README.md
2. In order to stage a release of wheels to pypi, you need to build a tagged release: `git tag v1.5 && git push --tags` will do it

**Comment by jxz12** [comment]
Those badges look great, I will work on getting them included. As for the release, I'm currently having a few issues with getting Appveyor installed, butI'll tag as soon as that's sorted.

**Comment by scottgigante** [comment]
Just saw that the builds are mostly up, nice work! I noticed that there were a couple of errors in the linux wheel builds, though. E.g.

https://travis-ci.com/jxz12/s_gd2/jobs/263193628#L707
https://travis-ci.com/jxz12/s_gd2/jobs/263193628#L969
https://travis-ci.com/jxz12/s_gd2/jobs/263193628#L1138

Looks like two issues. One related to testing the wheel once built which relates to matplotlib and is kind of weird. The other is a bunch of system requirements which should be added at the top of `build_wheels.sh` for matplotlib compatibility. 

One temporary solution would be to comment out lines https://github.com/jxz12/s_gd2/blob/master/travis/build-wheels.sh#L36 to https://github.com/jxz12/s_gd2/blob/master/travis/build-wheels.sh#L43. Otherwise you'll have to work out what's going on with matplotlib.

**Comment by jxz12** [comment]
What do you think about simply removing matplotlib from the `install_requires` field - would that fix these little issues as well? It makes sense to me to leave both it and pycairo from any requires because they are only used for rendering in .png, which is separate from the main objective of the code.

**Comment by scottgigante** [comment]
That's certainly a valid option. You would have to include some additional try/except blocks to check for matplotlib, and if neither matplotlib nor cairo were installed through some kind of nice error (or maybe just run draw_svg?)

**Pull request merged**
