### PR TITLE
Add wheels for python 3.8, 3.9

### PR DESCRIPTION
**Pull request by scottgigante**
I've added deployment code for python 3.8 and 3.9, including migrating some of the deployment over to GitHub Actions. Especially relevant since Travis CI is no longer free.

### CODE REVIEW

**Comment by scottgigante** [comment]
Note: all changes to .py files are just modifications by my linter.

**Comment by scottgigante** [comment]
Okay I think this is good to go. Note that you'll need to create API tokens for pypi (https://pypi.org/account/login/?next=%2Fmanage%2Faccount%2Ftoken%2F) and testpypi (https://test.pypi.org/account/login/?next=%2Fmanage%2Faccount%2Ftoken%2F) and set them in github secrets (https://github.com/jxz12/s_gd2/settings/secrets/actions) as well as in travis.

**Comment by jxz12** [comment]
I've added the tokens as `pypi_password` and `test_pypi_password`, but how do I test if it works? I guess merge and then see if the upload succeeds

**Comment by scottgigante** [comment]
Yep -- the GH Action will run on `master`/`test_deploy` (testpypi) and any tag (pypi).

**Comment by jxz12** [comment]
Great and thank you so much! I'll merge as soon as the Travis build finishes.

**Comment by scottgigante** [comment]
Awesome, thanks! If you don't mind tagging `1.8.0.post1` that will push those wheels to pypi.

**Comment by jxz12** [comment]
Done! I think, does the `post1` suffix mean something in particular?

**Comment by scottgigante** [comment]
Thanks! See https://www.python.org/dev/peps/pep-0440/#post-releases

**Pull request merged**
